language: python

python:
     - "3.6.8"

env:
    - SECRET_KEY='TEST'

before_install:
    - python -m pip install --upgrade pip

install:
    - pipenv install
    - pip install -r requirements.txt

script:
    - python manage.py test

